<a href="https://colab.research.google.com/github/XL636/Neural-network-learning-/blob/main/Deep_learning_Pytorch_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Math Operations
* Add, Subtract, Multiply, Divide, Remainders, Exponents
* Shorthand and LongHand
* Reassignment

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [3]:
# Add
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [5]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [7]:
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [8]:
# Mul
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [9]:
torch.multiply(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [10]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [12]:
torch.divide(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [13]:
# Module
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [16]:
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [17]:
# Exponenets / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [20]:
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])