<a href="https://colab.research.google.com/github/XL636/Neural-network-learning-/blob/main/Deep_learning_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [4]:
my_torch = torch.arange(10) # 1 dimention (10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Reshape and View
my_torch = my_torch.reshape(2,5) # 2 dimention (2,5)
my_torch, my_torch.shape

(tensor([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]),
 torch.Size([2, 5]))

In [15]:
# Reshape if we don't know the number of item using -1
my_torch2 = torch.arange(12)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
my_torch2 = my_torch2.reshape(3,-1) # 2 dimention (3,4)
my_torch2, my_torch2.shape

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 torch.Size([3, 4]))

In [21]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

# Question:
* what is the different between view and reshape?

In [40]:
# with reshape and view, they will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
my_torch6 = my_torch5.reshape(2,5) # 2 dimention (2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [42]:
my_torch5[2] = 23
my_torch6

tensor([[ 0,  1, 23,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [27]:
# Slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# Grab specifit item
my_torch7[7]

tensor(7)

In [29]:
my_torch8 = my_torch7.reshape(5,2) # 2dimention
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [30]:
my_torch8[:,1] # 所有行的第一列 但是变成了向list一样的东西

tensor([1, 3, 5, 7, 9])

In [31]:
# Return column
my_torch8[:,1:] #这样就是二维了(5,1)

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [44]:
import torch

x = torch.arange(6).reshape(2,3)
print("x:\n", x)

print("\nIs x contiguous? ", x.is_contiguous())
print("Is x.t() contiguous? ", x.t().is_contiguous())

# 下面这行会报错：
# y1 = x.t().view(6)

# 正确做法：
y1 = x.t().contiguous().view(6)
print("\ny1 after contiguous + view:\n", y1)

# 对比：
y2 = x.view(2,3)
print("\ny2 from view directly:\n", y2)


x:
 tensor([[0, 1, 2],
        [3, 4, 5]])

Is x contiguous?  True
Is x.t() contiguous?  False

y1 after contiguous + reshape:
 tensor([0, 3, 1, 4, 2, 5])

y2 from view directly:
 tensor([[0, 1, 2],
        [3, 4, 5]])


# 最终问题
* 弄明白stride